language: python
python:
  # Don't try with older versions, as they don't seem to be compatible with **r type params in functions
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
install:
  - pip install pipenv
  - pipenv install
services:
  - redis-server
script:
  - pipenv run src/consume-mail.py -d test_inbound
  - cat consume-mail.log

branches:
  only:
    - master