Return-Path: <bounces@stevet-spe-send.trymsys.net>
Received: from mta1a2.demo-t.sparkpostelite.com (172.31.7.50) by ip-172-31-4-82.us-west-2.compute.internal id h2lul42evlsj for <test+32991901266478036392@not-gmail.com.bouncy-sink.trymsys.net>; Mon, 4 Jun 2018 17:56:34 +0000 (envelope-from <bounces@stevet-spe-send.trymsys.net>)
Authentication-Results: ip-172-31-4-82.us-west-2.compute.internal; spf=softfail smtp.mailfrom=bounces@stevet-spe-send.trymsys.net;
 dkim=pass (matches From: traffic.gen.subacc26@stevet-spe-send.trymsys.net) header.i=@stevet-spe-send.trymsys.net
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
	d=stevet-spe-send.trymsys.net; s=scph0418; t=1528134994;
	i=@stevet-spe-send.trymsys.net;
	bh=oB3T+QpHJPpFxoBSV1F8752cCa90HrVGXTB13zXm8jc=;
	h=To:Date:Subject:From:List-Unsubscribe:List-Id;
	b=et14GLPng5kE25V+Nj3K9g/ljOqxqDeSiS4kxdI7duHSUBhpvV1nk9PCpET2Hw31C
	 3BlLcQZ/ykUoOH6Tl51DFjHmXFuS/rnn19Z3vJevMbefagzs67Q0yUd6JhH9Z2CQB7
	 aOxVn5QCqjFh7HkO1VceBDX+Ns1SaH/MXCxho0Bo=
X-MSFBL: KZA7nd53Fw/GDfWYz9wlbQ9KWWsnvEiH6TBrOgm2eSQ=|eyJzdWJhY2NvdW50X2l
	kIjoiMjYiLCJyIjoidGVzdCszMjk5MTkwMTI2NjQ3ODAzNjM5MkBub3QtZ21haWw
	uY29tLmJvdW5jeS1zaW5rLnRyeW1zeXMubmV0IiwibWVzc2FnZV9pZCI6IjAwMDE
	1MjdkMTU1YjExOWQ1ZWQyIiwidGVuYW50X2lkIjoiZGVtbyIsImN1c3RvbWVyX2l
	kIjoiMSJ9
To: test+32991901266478036392@not-gmail.com.bouncy-sink.trymsys.net
Message-ID: <E5.2D.40209.25D751B5@a.mta2vrest.cc.prd.sparkpost>
Date: Mon, 04 Jun 2018 17:56:30 +0000
Content-Type: multipart/alternative; boundary="_----m+P6qcQR05uVyGs/athAPQ===_FB/3C-40209-E4D751B5"
MIME-Version: 1.0
Subject: Newsletter
From: traffic.gen.subacc26@stevet-spe-send.trymsys.net
List-Unsubscribe: <mailto:unsubscribe@demo-t.sparkpostelite.com?subject=unsubscribe:ZLiSJKcGhRPpLNmGQ8ORz8n9caa9dNjqfQbwGDXqEHg~|eyAicmNwdF90byI6ICJ0ZXN0KzMyOTkxOTAxMjY2NDc4MDM2MzkyQG5vdC1nbWFpbC5jb20uYm91bmN5LXNpbmsudHJ5bXN5cy5uZXQiLCAidGVuYW50X2lkIjogImRlbW8iLCAiY3VzdG9tZXJfaWQiOiAiMSIsICJzdWJhY2NvdW50X2lkIjogIjI2IiwgIm1lc3NhZ2VfaWQiOiAiMDAwMTUyN2QxNTViMTE5ZDVlZDIiIH0~>
List-Id: <demo-1-26>

--_----m+P6qcQR05uVyGs/athAPQ===_FB/3C-40209-E4D751B5
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

hello world
--_----m+P6qcQR05uVyGs/athAPQ===_FB/3C-40209-E4D751B5
Content-Transfer-Encoding: 7bit
Content-Type: text/html; charset="UTF-8"

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>test mail</title>
  </head>
  <body>
<div style="color:transparent;visibility:hidden;opacity:0;font-size:0px;border:0;max-height:1px;width:1px;margin:0px;padding:0px;border-width:0px!important;display:none!important;line-height:0px!important;"><img border="0" width="1" height="1" src="http://click.hp2demo.trymsys.net/q/sqON9nkulCMEsibLSYeHoA~~/AAAAAQA~/RgRc-AJOPVcEZGVtb1gEAAAAGkIKAAFSfRVbEZ1e0lI_dGVzdCszMjk5MTkwMTI2NjQ3ODAzNjM5MkBub3QtZ21haWwuY29tLmJvdW5jeS1zaW5rLnRyeW1zeXMubmV0"/></div>

    Click <a href="http://click.hp2demo.trymsys.net/f/a/7zD80MgbvwHh4lqRkCM6mg~~/AAAAAQA~/RgRc-AJOP0UPTW9yZSBEYWlseSBOZXdzRB1odHRwOi8vZXhhbXBsZS5jb20vaW5kZXguaHRtbFcEZGVtb1gEAAAAGkIKAAFSfRVbEZ1e0lI_dGVzdCszMjk5MTkwMTI2NjQ3ODAzNjM5MkBub3QtZ21haWwuY29tLmJvdW5jeS1zaW5rLnRyeW1zeXMubmV0" >http://example.com/index.html</a>
  
<img border="0" width="1" height="1" alt="" src="http://click.hp2demo.trymsys.net/q/mYgXrrwl6mCSUEr-MW5cJw~~/AAAAAQA~/RgRc-AJOPlcEZGVtb1gEAAAAGkIKAAFSfRVbEZ1e0lI_dGVzdCszMjk5MTkwMTI2NjQ3ODAzNjM5MkBub3QtZ21haWwuY29tLmJvdW5jeS1zaW5rLnRyeW1zeXMubmV0">
</body>
</html>
--_----m+P6qcQR05uVyGs/athAPQ===_FB/3C-40209-E4D751B5--

